#!/bin/bash
cd "$(dirname "$0")"

OLD_SOURCE="https://mirrors.ustc.edu.cn/ubuntu-old-releases/ubuntu/pool/main/g/glibc"
OLD_SOURCE_SRC="https://mirrors.ustc.edu.cn/ubuntu-old-releases/ubuntu/pool/universe/g/glibc"

SOURCE="https://mirrors.ustc.edu.cn/ubuntu/pool/main/g/glibc"
SOURCE_SRC="https://mirrors.ustc.edu.cn/ubuntu/pool/universe/g/glibc"
# Use the source below if you feel slow, or change it on your own.
# SOURCE="http://archive.ubuntu.com/ubuntu/pool/main/g/glibc/"

usage() {
  echo >&2 "Usage: $0 (all|new|old) [id]"
  exit 2
}

download_old() {
  ./download_single $1 $OLD_SOURCE $OLD_SOURCE_SRC
}
download_new() {
  ./download_single $1 $SOURCE $SOURCE_SRC
}

download_old_all() {
  while read p; do
    download_old $p 
  done <old_list
}

download_new_all() {
  while read p; do
    download_new $p
  done <list
}

if [[ $1 == "all" ]]; then
  download_new_all
  download_old_all
elif [[ $1 == "old" ]]; then
  if [[ $# == 1 ]]; then
    download_old_all
  elif [[ $# == 2 ]]; then
    download_old $2
  else
    usage
  fi
elif [[ $1 == "new" ]]; then
  if [[ $# == 1 ]]; then
    download_new_all
  elif [[ $# == 2 ]]; then
    download_new $2
  else
    usage
  fi
else
  usage
fi